LevMax = 1;
LevCount = 10;
levels : array [1..10,1..2] of string = (

  ('10','I am recognised universally as the eminent person in my field'),
  (' 9','Postdoctoral degree, such as a DLitt, etc.'),
  (' 8','Over qualified to work any job with a Ph.D.'),
  (' 7','Honours or a Masters degree grad.'),
  (' 6','Managed to finish my bachelors/postgrad diploma or apprenticeship.'),
  (' 5','Learned it the hard way and I`m now an expert...'),
  (' 4','Finished a short-course (2 years or less)'),
  (' 3','Started a degree or short course, and plan to finish it some day.'),
  (' 2','Learned it the hard way and now planning my future in this field'),
  (' 1','I`m a half-wit when it comes to this.'));

