genplas.rad 1: 
genplas.rad 2: 
genplas.rad 3: 
genplas.rad 4: 
genplas.rad 5: 
genplas.rad 6: 
genplas.rad 7: 
genplas.rad 8: 
genplas.rad 9: 
genplas.rad 10: 
genplas.rad 11: 
genplas.rad 12: 
genplas.rad 13: 
genplas.rad 14: 
genplas.rad 15: 
genplas.rad 16: 
genplas.rad 17: 
genplas.rad 18: 
genplas.rad 19: 
genplas.rad 20: 
C:\BC45\INCLUDE\stdio.h 1: 
C:\BC45\INCLUDE\stdio.h 2: 
C:\BC45\INCLUDE\stdio.h 3: 
C:\BC45\INCLUDE\stdio.h 4: 
C:\BC45\INCLUDE\stdio.h 5: 
C:\BC45\INCLUDE\stdio.h 6: 
C:\BC45\INCLUDE\stdio.h 7: 
C:\BC45\INCLUDE\stdio.h 8: 
C:\BC45\INCLUDE\stdio.h 9: 
C:\BC45\INCLUDE\stdio.h 10: 
C:\BC45\INCLUDE\stdio.h 11: 
C:\BC45\INCLUDE\stdio.h 12: 
C:\BC45\INCLUDE\stdio.h 13: 
C:\BC45\INCLUDE\stdio.h 14: 
C:\BC45\INCLUDE\stdio.h 15: 
C:\BC45\INCLUDE\stdio.h 16: 
C:\BC45\INCLUDE\stdio.h 17: 
C:\BC45\INCLUDE\stdio.h 18: 
C:\BC45\INCLUDE\stdio.h 19: 
C:\BC45\INCLUDE\_defs.h 1: 
C:\BC45\INCLUDE\_defs.h 2: 
C:\BC45\INCLUDE\_defs.h 3: 
C:\BC45\INCLUDE\_defs.h 4: 
C:\BC45\INCLUDE\_defs.h 5: 
C:\BC45\INCLUDE\_defs.h 6: 
C:\BC45\INCLUDE\_defs.h 7: 
C:\BC45\INCLUDE\_defs.h 8: 
C:\BC45\INCLUDE\_defs.h 9: 
C:\BC45\INCLUDE\_defs.h 10: 
C:\BC45\INCLUDE\_defs.h 11: 
C:\BC45\INCLUDE\_defs.h 12: 
C:\BC45\INCLUDE\_defs.h 13: 
C:\BC45\INCLUDE\_defs.h 14: 
C:\BC45\INCLUDE\_defs.h 15: 
C:\BC45\INCLUDE\_defs.h 16: 
C:\BC45\INCLUDE\_defs.h 17: 
C:\BC45\INCLUDE\_defs.h 18: 
C:\BC45\INCLUDE\_defs.h 19: 
C:\BC45\INCLUDE\_defs.h 20: 
C:\BC45\INCLUDE\_defs.h 21: 
C:\BC45\INCLUDE\_defs.h 22: 
C:\BC45\INCLUDE\_defs.h 23: 
C:\BC45\INCLUDE\_defs.h 24: 
C:\BC45\INCLUDE\_defs.h 25: 
C:\BC45\INCLUDE\_defs.h 26: 
C:\BC45\INCLUDE\_defs.h 27: 
C:\BC45\INCLUDE\_defs.h 28: 
C:\BC45\INCLUDE\_defs.h 29: 
C:\BC45\INCLUDE\_defs.h 30: 
C:\BC45\INCLUDE\_defs.h 31: 
C:\BC45\INCLUDE\_defs.h 32: 
C:\BC45\INCLUDE\_defs.h 33: 
C:\BC45\INCLUDE\_defs.h 34: 
C:\BC45\INCLUDE\_defs.h 35: 
C:\BC45\INCLUDE\_defs.h 36: 
C:\BC45\INCLUDE\_defs.h 37: 
C:\BC45\INCLUDE\_defs.h 38: 
C:\BC45\INCLUDE\_defs.h 39: 
C:\BC45\INCLUDE\_defs.h 40: 
C:\BC45\INCLUDE\_defs.h 41: 
C:\BC45\INCLUDE\_defs.h 42: 
C:\BC45\INCLUDE\_defs.h 43: 
C:\BC45\INCLUDE\_defs.h 44: 
C:\BC45\INCLUDE\_defs.h 45: 
C:\BC45\INCLUDE\_defs.h 46: 
C:\BC45\INCLUDE\_defs.h 47: 
C:\BC45\INCLUDE\_defs.h 48: 
C:\BC45\INCLUDE\_defs.h 49: 
C:\BC45\INCLUDE\_defs.h 50: 
C:\BC45\INCLUDE\_defs.h 51: 
C:\BC45\INCLUDE\_defs.h 52: 
C:\BC45\INCLUDE\_defs.h 53: 
C:\BC45\INCLUDE\_defs.h 54: 
C:\BC45\INCLUDE\_defs.h 55: 
C:\BC45\INCLUDE\_defs.h 56: 
C:\BC45\INCLUDE\_defs.h 57: 
C:\BC45\INCLUDE\_defs.h 58: 
C:\BC45\INCLUDE\_defs.h 59: 
C:\BC45\INCLUDE\_defs.h 60: 
C:\BC45\INCLUDE\_defs.h 61: 
C:\BC45\INCLUDE\_defs.h 62: 
C:\BC45\INCLUDE\_defs.h 63: 
C:\BC45\INCLUDE\_defs.h 64: 
C:\BC45\INCLUDE\_defs.h 65: 
C:\BC45\INCLUDE\_defs.h 66: 
C:\BC45\INCLUDE\_defs.h 67: 
C:\BC45\INCLUDE\_defs.h 68: 
C:\BC45\INCLUDE\_defs.h 69: 
C:\BC45\INCLUDE\_defs.h 70: 
C:\BC45\INCLUDE\_defs.h 71: 
C:\BC45\INCLUDE\_defs.h 72: 
C:\BC45\INCLUDE\_defs.h 73: 
C:\BC45\INCLUDE\_defs.h 74: 
C:\BC45\INCLUDE\_defs.h 75: 
C:\BC45\INCLUDE\_defs.h 76: 
C:\BC45\INCLUDE\_defs.h 77: 
C:\BC45\INCLUDE\_defs.h 78: 
C:\BC45\INCLUDE\_defs.h 79: 
C:\BC45\INCLUDE\_defs.h 80: 
C:\BC45\INCLUDE\_defs.h 81: 
C:\BC45\INCLUDE\_defs.h 82: 
C:\BC45\INCLUDE\_defs.h 83: 
C:\BC45\INCLUDE\_defs.h 84: 
C:\BC45\INCLUDE\_defs.h 85: 
C:\BC45\INCLUDE\_defs.h 86:   
C:\BC45\INCLUDE\_defs.h 87: 
C:\BC45\INCLUDE\_defs.h 88: 
C:\BC45\INCLUDE\_defs.h 89: 
C:\BC45\INCLUDE\_defs.h 90:     
C:\BC45\INCLUDE\_defs.h 91: 
C:\BC45\INCLUDE\_defs.h 92: 
C:\BC45\INCLUDE\_defs.h 93: 
C:\BC45\INCLUDE\_defs.h 94: 
C:\BC45\INCLUDE\_defs.h 95: 
C:\BC45\INCLUDE\_defs.h 96: 
C:\BC45\INCLUDE\_defs.h 97: 
C:\BC45\INCLUDE\_defs.h 98: 
C:\BC45\INCLUDE\_defs.h 99: 
C:\BC45\INCLUDE\_defs.h 100: 
C:\BC45\INCLUDE\_defs.h 101: 
C:\BC45\INCLUDE\_defs.h 102: 
C:\BC45\INCLUDE\_defs.h 103: 
C:\BC45\INCLUDE\_defs.h 104: 
C:\BC45\INCLUDE\_defs.h 105: 
C:\BC45\INCLUDE\_defs.h 106: 
C:\BC45\INCLUDE\_defs.h 107: 
C:\BC45\INCLUDE\_defs.h 108: 
C:\BC45\INCLUDE\_defs.h 109: 
C:\BC45\INCLUDE\_defs.h 110:   
C:\BC45\INCLUDE\_defs.h 111: 
C:\BC45\INCLUDE\_defs.h 112: 
C:\BC45\INCLUDE\_defs.h 113: 
C:\BC45\INCLUDE\_defs.h 114: 
C:\BC45\INCLUDE\_defs.h 115: 
C:\BC45\INCLUDE\_defs.h 116: 
C:\BC45\INCLUDE\_defs.h 117: 
C:\BC45\INCLUDE\_defs.h 118: 
C:\BC45\INCLUDE\_defs.h 119: 
C:\BC45\INCLUDE\_defs.h 120: 
C:\BC45\INCLUDE\_defs.h 121: 
C:\BC45\INCLUDE\_defs.h 122: 
C:\BC45\INCLUDE\_defs.h 123: 
C:\BC45\INCLUDE\_defs.h 124: 
C:\BC45\INCLUDE\_defs.h 125: 
C:\BC45\INCLUDE\_defs.h 126: 
C:\BC45\INCLUDE\_defs.h 127: 
C:\BC45\INCLUDE\_defs.h 128: 
C:\BC45\INCLUDE\_defs.h 129: 
C:\BC45\INCLUDE\_defs.h 130: 
C:\BC45\INCLUDE\_defs.h 131: 
C:\BC45\INCLUDE\_defs.h 132: 
C:\BC45\INCLUDE\_defs.h 133: 
C:\BC45\INCLUDE\_defs.h 134: 
C:\BC45\INCLUDE\_defs.h 135: 
C:\BC45\INCLUDE\_defs.h 136: 
C:\BC45\INCLUDE\_defs.h 137: 
C:\BC45\INCLUDE\_defs.h 138: 
C:\BC45\INCLUDE\_defs.h 139:   
C:\BC45\INCLUDE\_defs.h 140: 
C:\BC45\INCLUDE\_defs.h 141: 
C:\BC45\INCLUDE\_defs.h 142: 
C:\BC45\INCLUDE\_defs.h 143: 
C:\BC45\INCLUDE\_defs.h 144: 
C:\BC45\INCLUDE\_defs.h 145: 
C:\BC45\INCLUDE\_defs.h 146: 
C:\BC45\INCLUDE\_defs.h 147: 
C:\BC45\INCLUDE\_defs.h 148: 
C:\BC45\INCLUDE\_defs.h 149: 
C:\BC45\INCLUDE\_defs.h 150: 
C:\BC45\INCLUDE\_defs.h 151: 
C:\BC45\INCLUDE\_defs.h 152: 
C:\BC45\INCLUDE\_defs.h 153: 
C:\BC45\INCLUDE\_defs.h 154: 
C:\BC45\INCLUDE\_defs.h 155: 
C:\BC45\INCLUDE\_defs.h 156: 
C:\BC45\INCLUDE\_defs.h 157: 
C:\BC45\INCLUDE\_defs.h 158: 
C:\BC45\INCLUDE\_defs.h 159: 
C:\BC45\INCLUDE\_defs.h 160: 
C:\BC45\INCLUDE\_defs.h 161: 
C:\BC45\INCLUDE\_defs.h 162: 
C:\BC45\INCLUDE\_defs.h 163: 
C:\BC45\INCLUDE\_defs.h 164: 
C:\BC45\INCLUDE\_defs.h 165: 
C:\BC45\INCLUDE\_defs.h 166: 
C:\BC45\INCLUDE\_defs.h 167: 
C:\BC45\INCLUDE\_defs.h 168: 
C:\BC45\INCLUDE\_defs.h 169: 
C:\BC45\INCLUDE\_defs.h 170: 
C:\BC45\INCLUDE\_defs.h 171: 
C:\BC45\INCLUDE\_defs.h 172: 
C:\BC45\INCLUDE\_defs.h 173: 
C:\BC45\INCLUDE\_defs.h 174: 
C:\BC45\INCLUDE\_defs.h 175: 
C:\BC45\INCLUDE\_defs.h 176: 
C:\BC45\INCLUDE\_defs.h 177: 
C:\BC45\INCLUDE\_defs.h 178: 
C:\BC45\INCLUDE\stdio.h 20: 
C:\BC45\INCLUDE\stdio.h 21: 
C:\BC45\INCLUDE\stdio.h 22: 
C:\BC45\INCLUDE\stdio.h 23: 
C:\BC45\INCLUDE\_nfile.h 1: 
C:\BC45\INCLUDE\_nfile.h 2: 
C:\BC45\INCLUDE\_nfile.h 3: 
C:\BC45\INCLUDE\_nfile.h 4: 
C:\BC45\INCLUDE\_nfile.h 5: 
C:\BC45\INCLUDE\_nfile.h 6: 
C:\BC45\INCLUDE\_nfile.h 7: 
C:\BC45\INCLUDE\_nfile.h 8: 
C:\BC45\INCLUDE\_nfile.h 9: 
C:\BC45\INCLUDE\_nfile.h 10: 
C:\BC45\INCLUDE\_nfile.h 11: 
C:\BC45\INCLUDE\_nfile.h 12: 
C:\BC45\INCLUDE\_nfile.h 13: 
C:\BC45\INCLUDE\_nfile.h 14: 
C:\BC45\INCLUDE\_nfile.h 15: 
C:\BC45\INCLUDE\_nfile.h 16: 
C:\BC45\INCLUDE\_nfile.h 17: 
C:\BC45\INCLUDE\_nfile.h 18: 
C:\BC45\INCLUDE\_nfile.h 19: 
C:\BC45\INCLUDE\_nfile.h 20: 
C:\BC45\INCLUDE\_nfile.h 21: 
C:\BC45\INCLUDE\_nfile.h 22: 
C:\BC45\INCLUDE\_nfile.h 23: 
C:\BC45\INCLUDE\_nfile.h 24: 
C:\BC45\INCLUDE\_nfile.h 25: 
C:\BC45\INCLUDE\_nfile.h 26: 
C:\BC45\INCLUDE\_nfile.h 27: 
C:\BC45\INCLUDE\_nfile.h 28: 
C:\BC45\INCLUDE\_nfile.h 29: 
C:\BC45\INCLUDE\_nfile.h 30: 
C:\BC45\INCLUDE\stdio.h 24: 
C:\BC45\INCLUDE\stdio.h 25: 
C:\BC45\INCLUDE\stdio.h 26: 
C:\BC45\INCLUDE\stdio.h 27: 
C:\BC45\INCLUDE\_null.h 1: 
C:\BC45\INCLUDE\_null.h 2: 
C:\BC45\INCLUDE\_null.h 3: 
C:\BC45\INCLUDE\_null.h 4: 
C:\BC45\INCLUDE\_null.h 5: 
C:\BC45\INCLUDE\_null.h 6: 
C:\BC45\INCLUDE\_null.h 7: 
C:\BC45\INCLUDE\_null.h 8: 
C:\BC45\INCLUDE\_null.h 9: 
C:\BC45\INCLUDE\_null.h 10: 
C:\BC45\INCLUDE\_null.h 11: 
C:\BC45\INCLUDE\_null.h 12: 
C:\BC45\INCLUDE\_null.h 13: 
C:\BC45\INCLUDE\_null.h 14: 
C:\BC45\INCLUDE\_null.h 15: 
C:\BC45\INCLUDE\_null.h 16: 
C:\BC45\INCLUDE\_null.h 17:     
C:\BC45\INCLUDE\_null.h 18: 
C:\BC45\INCLUDE\_null.h 19: 
C:\BC45\INCLUDE\_null.h 20: 
C:\BC45\INCLUDE\_null.h 21: 
C:\BC45\INCLUDE\_null.h 22: 
C:\BC45\INCLUDE\_null.h 23: 
C:\BC45\INCLUDE\_null.h 24: 
C:\BC45\INCLUDE\_null.h 25: 
C:\BC45\INCLUDE\_null.h 26: 
C:\BC45\INCLUDE\_null.h 27: 
C:\BC45\INCLUDE\_null.h 28: 
C:\BC45\INCLUDE\_null.h 29: 
C:\BC45\INCLUDE\_null.h 30: 
C:\BC45\INCLUDE\_null.h 31: 
C:\BC45\INCLUDE\_null.h 32: 
C:\BC45\INCLUDE\stdio.h 28: 
C:\BC45\INCLUDE\stdio.h 29: 
C:\BC45\INCLUDE\stdio.h 30: 
C:\BC45\INCLUDE\stdio.h 31: 
C:\BC45\INCLUDE\stdio.h 32: 
C:\BC45\INCLUDE\stdio.h 33: 
C:\BC45\INCLUDE\stdio.h 34: 
C:\BC45\INCLUDE\stdio.h 35: 
C:\BC45\INCLUDE\stdio.h 36: 
C:\BC45\INCLUDE\stdio.h 37: #pragma option -a-
C:\BC45\INCLUDE\stdio.h 38: 
C:\BC45\INCLUDE\stdio.h 39: 
C:\BC45\INCLUDE\stdio.h 40: 
C:\BC45\INCLUDE\stdio.h 41: 
C:\BC45\INCLUDE\stdio.h 42: 
C:\BC45\INCLUDE\stdio.h 43: 
C:\BC45\INCLUDE\stdio.h 44: typedef unsigned size_t;
C:\BC45\INCLUDE\stdio.h 45: 
C:\BC45\INCLUDE\stdio.h 46: 
C:\BC45\INCLUDE\stdio.h 47: 
C:\BC45\INCLUDE\stdio.h 48: 
C:\BC45\INCLUDE\stdio.h 49: typedef long    fpos_t;
C:\BC45\INCLUDE\stdio.h 50: 
C:\BC45\INCLUDE\stdio.h 51: 
C:\BC45\INCLUDE\stdio.h 52: 
C:\BC45\INCLUDE\stdio.h 53: 
C:\BC45\INCLUDE\stdio.h 54: extern int _floatconvert;
C:\BC45\INCLUDE\stdio.h 55: 
C:\BC45\INCLUDE\stdio.h 56: 
C:\BC45\INCLUDE\stdio.h 57: 
C:\BC45\INCLUDE\stdio.h 58: 
C:\BC45\INCLUDE\stdio.h 59: 
C:\BC45\INCLUDE\stdio.h 60: 
C:\BC45\INCLUDE\stdio.h 61: 
C:\BC45\INCLUDE\stdio.h 62: 
C:\BC45\INCLUDE\stdio.h 63: 
C:\BC45\INCLUDE\stdio.h 64: 
C:\BC45\INCLUDE\stdio.h 65: 
C:\BC45\INCLUDE\stdio.h 66: 
C:\BC45\INCLUDE\stdio.h 67: 
C:\BC45\INCLUDE\stdio.h 68: 
C:\BC45\INCLUDE\stdio.h 69: 
C:\BC45\INCLUDE\stdio.h 70: 
C:\BC45\INCLUDE\stdio.h 71: 
C:\BC45\INCLUDE\stdio.h 72: 
C:\BC45\INCLUDE\stdio.h 73: 
C:\BC45\INCLUDE\stdio.h 74: 
C:\BC45\INCLUDE\stdio.h 75: 
C:\BC45\INCLUDE\stdio.h 76: 
C:\BC45\INCLUDE\stdio.h 77: 
C:\BC45\INCLUDE\stdio.h 78: 
C:\BC45\INCLUDE\stdio.h 79: 
C:\BC45\INCLUDE\stdio.h 80: 
C:\BC45\INCLUDE\stdio.h 81: 
C:\BC45\INCLUDE\stdio.h 82: 
C:\BC45\INCLUDE\stdio.h 83: 
C:\BC45\INCLUDE\stdio.h 84: 
C:\BC45\INCLUDE\stdio.h 85: 
C:\BC45\INCLUDE\stdio.h 86: 
C:\BC45\INCLUDE\stdio.h 87: 
C:\BC45\INCLUDE\stdio.h 88: 
C:\BC45\INCLUDE\stdio.h 89: 
C:\BC45\INCLUDE\stdio.h 90: 
C:\BC45\INCLUDE\stdio.h 91: 
C:\BC45\INCLUDE\stdio.h 92: 
C:\BC45\INCLUDE\stdio.h 93: 
C:\BC45\INCLUDE\stdio.h 94: 
C:\BC45\INCLUDE\stdio.h 95: 
C:\BC45\INCLUDE\stdio.h 96: 
C:\BC45\INCLUDE\stdio.h 97: 
C:\BC45\INCLUDE\stdio.h 98: 
C:\BC45\INCLUDE\stdio.h 99: 
C:\BC45\INCLUDE\stdio.h 100: 
C:\BC45\INCLUDE\stdio.h 101: 
C:\BC45\INCLUDE\stdio.h 102: 
C:\BC45\INCLUDE\stdio.h 103: 
C:\BC45\INCLUDE\stdio.h 104: 
C:\BC45\INCLUDE\stdio.h 105: typedef struct  {
C:\BC45\INCLUDE\stdio.h 106: int             level;          
C:\BC45\INCLUDE\stdio.h 107: unsigned        flags;          
C:\BC45\INCLUDE\stdio.h 108: char            fd;             
C:\BC45\INCLUDE\stdio.h 109: unsigned char   hold;           
C:\BC45\INCLUDE\stdio.h 110: int             bsize;          
C:\BC45\INCLUDE\stdio.h 111: unsigned char    *buffer;   
C:\BC45\INCLUDE\stdio.h 112: unsigned char    *curp;     
C:\BC45\INCLUDE\stdio.h 113: unsigned        istemp;         
C:\BC45\INCLUDE\stdio.h 114: short           token;          
C:\BC45\INCLUDE\stdio.h 115: }       FILE;                           
C:\BC45\INCLUDE\stdio.h 116: 
C:\BC45\INCLUDE\stdio.h 117: 
C:\BC45\INCLUDE\stdio.h 118: 
C:\BC45\INCLUDE\stdio.h 119: 
C:\BC45\INCLUDE\stdio.h 120: 
C:\BC45\INCLUDE\stdio.h 121: 
C:\BC45\INCLUDE\stdio.h 122: 
C:\BC45\INCLUDE\stdio.h 123: 
C:\BC45\INCLUDE\stdio.h 124: 
C:\BC45\INCLUDE\stdio.h 125: 
C:\BC45\INCLUDE\stdio.h 126: 
C:\BC45\INCLUDE\stdio.h 127: 
C:\BC45\INCLUDE\stdio.h 128: 
C:\BC45\INCLUDE\stdio.h 129: 
C:\BC45\INCLUDE\stdio.h 130: 
C:\BC45\INCLUDE\stdio.h 131: 
C:\BC45\INCLUDE\stdio.h 132: extern  FILE    __cdecl _streams[];
C:\BC45\INCLUDE\stdio.h 133: extern  unsigned    __cdecl _nfile;
C:\BC45\INCLUDE\stdio.h 134: 
C:\BC45\INCLUDE\stdio.h 135: 
C:\BC45\INCLUDE\stdio.h 136: 
C:\BC45\INCLUDE\stdio.h 137: 
C:\BC45\INCLUDE\stdio.h 138: 
C:\BC45\INCLUDE\stdio.h 139: 
C:\BC45\INCLUDE\stdio.h 140: 
C:\BC45\INCLUDE\stdio.h 141: 
C:\BC45\INCLUDE\stdio.h 142: 
C:\BC45\INCLUDE\stdio.h 143: 
C:\BC45\INCLUDE\stdio.h 144: 
C:\BC45\INCLUDE\stdio.h 145: 
C:\BC45\INCLUDE\stdio.h 146: 
C:\BC45\INCLUDE\stdio.h 147: 
C:\BC45\INCLUDE\stdio.h 148: 
C:\BC45\INCLUDE\stdio.h 149: 
C:\BC45\INCLUDE\stdio.h 150: 
C:\BC45\INCLUDE\stdio.h 151: 
C:\BC45\INCLUDE\stdio.h 152: 
C:\BC45\INCLUDE\stdio.h 153: 
C:\BC45\INCLUDE\stdio.h 154: 
C:\BC45\INCLUDE\stdio.h 155: 
C:\BC45\INCLUDE\stdio.h 156: 
C:\BC45\INCLUDE\stdio.h 157: 
C:\BC45\INCLUDE\stdio.h 158: 
C:\BC45\INCLUDE\stdio.h 159: 
C:\BC45\INCLUDE\stdio.h 160: void    __cdecl          clearerr(FILE  *__stream);
C:\BC45\INCLUDE\stdio.h 161: int     __cdecl  fclose(FILE  *__stream);
C:\BC45\INCLUDE\stdio.h 162: int     __cdecl  fflush(FILE  *__stream);
C:\BC45\INCLUDE\stdio.h 163: int     __cdecl  fgetc(FILE  *__stream);
C:\BC45\INCLUDE\stdio.h 164: int     __cdecl          fgetpos(FILE  *__stream, fpos_t  *__pos);
C:\BC45\INCLUDE\stdio.h 165: char    *__cdecl  fgets(char  *__s, int __n, FILE  *__stream);
C:\BC45\INCLUDE\stdio.h 166: FILE    *__cdecl  fopen(const char  *__path, const char  *__mode);
C:\BC45\INCLUDE\stdio.h 167: int     __cdecl  fprintf(FILE  *__stream, const char  *__format, ...);
C:\BC45\INCLUDE\stdio.h 168: int     __cdecl  fputc(int __c, FILE  *__stream);
C:\BC45\INCLUDE\stdio.h 169: int     __cdecl  fputs(const char  *__s, FILE  *__stream);
C:\BC45\INCLUDE\stdio.h 170: size_t  __cdecl  fread(void  *__ptr, size_t __size, size_t __n,
C:\BC45\INCLUDE\stdio.h 171: FILE  *__stream);
C:\BC45\INCLUDE\stdio.h 172: FILE    *__cdecl  freopen(const char  *__path, const char  *__mode,
C:\BC45\INCLUDE\stdio.h 173: FILE  *__stream);
C:\BC45\INCLUDE\stdio.h 174: int     __cdecl  fscanf(FILE  *__stream, const char  *__format, ...);
C:\BC45\INCLUDE\stdio.h 175: int     __cdecl  fseek(FILE  *__stream, long __offset, int __whence);
C:\BC45\INCLUDE\stdio.h 176: int     __cdecl          fsetpos(FILE  *__stream, const fpos_t  *__pos);
C:\BC45\INCLUDE\stdio.h 177: long    __cdecl  ftell(FILE  *__stream);
C:\BC45\INCLUDE\stdio.h 178: size_t  __cdecl  fwrite(const void  *__ptr, size_t __size, size_t __n,
C:\BC45\INCLUDE\stdio.h 179: FILE  *__stream);
C:\BC45\INCLUDE\stdio.h 180: char    *__cdecl     gets(char  *__s);
C:\BC45\INCLUDE\stdio.h 181: void    __cdecl          perror(const char  *__s);
C:\BC45\INCLUDE\stdio.h 182: int     __cdecl          printf(const char  *__format, ...);
C:\BC45\INCLUDE\stdio.h 183: int     __cdecl          puts(const char  *__s);
C:\BC45\INCLUDE\stdio.h 184: int     __cdecl         remove(const char  *__path);
C:\BC45\INCLUDE\stdio.h 185: int     __cdecl  rename(const char  *__oldname,const char  *__newname);
C:\BC45\INCLUDE\stdio.h 186: void    __cdecl  rewind(FILE  *__stream);
C:\BC45\INCLUDE\stdio.h 187: int     __cdecl          scanf(const char  *__format, ...);
C:\BC45\INCLUDE\stdio.h 188: void    __cdecl          setbuf(FILE  *__stream, char  *__buf);
C:\BC45\INCLUDE\stdio.h 189: int     __cdecl  setvbuf(FILE  *__stream, char  *__buf,
C:\BC45\INCLUDE\stdio.h 190: int __type, size_t __size);
C:\BC45\INCLUDE\stdio.h 191: int     __cdecl  sprintf(char  *__buffer, const char  *__format, ...);
C:\BC45\INCLUDE\stdio.h 192: int     __cdecl  sscanf(const char  *__buffer,
C:\BC45\INCLUDE\stdio.h 193: const char  *__format, ...);
C:\BC45\INCLUDE\stdio.h 194: char    *__cdecl  strerror(int __errnum);
C:\BC45\INCLUDE\stdio.h 195: FILE    *__cdecl  tmpfile(void);
C:\BC45\INCLUDE\stdio.h 196: char    *__cdecl  tmpnam(char  *__s);
C:\BC45\INCLUDE\stdio.h 197: int     __cdecl  ungetc(int __c, FILE  *__stream);
C:\BC45\INCLUDE\stdio.h 198: int     __cdecl  vfprintf(FILE  *__stream, const char  *__format,
C:\BC45\INCLUDE\stdio.h 199: void  *__arglist);
C:\BC45\INCLUDE\stdio.h 200: int     __cdecl  vfscanf(FILE  *__stream, const char  *__format,
C:\BC45\INCLUDE\stdio.h 201: void  *__arglist);
C:\BC45\INCLUDE\stdio.h 202: int     __cdecl         vprintf(const char  *__format, void  *__arglist);
C:\BC45\INCLUDE\stdio.h 203: int     __cdecl          vscanf(const char  *__format, void  *__arglist);
C:\BC45\INCLUDE\stdio.h 204: int     __cdecl  vsprintf(char  *__buffer, const char  *__format,
C:\BC45\INCLUDE\stdio.h 205: void  *__arglist);
C:\BC45\INCLUDE\stdio.h 206: int     __cdecl  vsscanf(const char  *__buffer, const char  *__format,
C:\BC45\INCLUDE\stdio.h 207: void  *__arglist);
C:\BC45\INCLUDE\stdio.h 208: int     __cdecl         unlink(const char  *__path);
C:\BC45\INCLUDE\stdio.h 209: int     __cdecl          getc(FILE  *__fp);
C:\BC45\INCLUDE\stdio.h 210: 
C:\BC45\INCLUDE\stdio.h 211: int     __cdecl          getchar(void);
C:\BC45\INCLUDE\stdio.h 212: int     __cdecl          putchar(const int __c);
C:\BC45\INCLUDE\stdio.h 213: 
C:\BC45\INCLUDE\stdio.h 214: int     __cdecl          putc(const int __c, FILE  *__fp);
C:\BC45\INCLUDE\stdio.h 215: int     __cdecl          feof(FILE  *__fp);
C:\BC45\INCLUDE\stdio.h 216: int     __cdecl          ferror(FILE  *__fp);
C:\BC45\INCLUDE\stdio.h 217: 
C:\BC45\INCLUDE\stdio.h 218: int     __cdecl  fcloseall(void);
C:\BC45\INCLUDE\stdio.h 219: FILE     *__cdecl  fdopen(int __handle, char  *__type);
C:\BC45\INCLUDE\stdio.h 220: int     __cdecl  fgetchar(void);
C:\BC45\INCLUDE\stdio.h 221: int     __cdecl  flushall(void);
C:\BC45\INCLUDE\stdio.h 222: int     __cdecl  fputchar(int __c);
C:\BC45\INCLUDE\stdio.h 223: FILE     * __cdecl   _fsopen (const char  *__path, const char  *__mode,
C:\BC45\INCLUDE\stdio.h 224: int __shflag);
C:\BC45\INCLUDE\stdio.h 225: int     __cdecl          getw(FILE  *__stream);
C:\BC45\INCLUDE\stdio.h 226: int     __cdecl          putw(int __w, FILE  *__stream);
C:\BC45\INCLUDE\stdio.h 227: int     __cdecl          rmtmp(void);
C:\BC45\INCLUDE\stdio.h 228: char     * __cdecl  _strerror(const char  *__s);
C:\BC45\INCLUDE\stdio.h 229: char     * __cdecl  tempnam(char  *__dir, char  *__pfx);
C:\BC45\INCLUDE\stdio.h 230: 
C:\BC45\INCLUDE\stdio.h 231: 
C:\BC45\INCLUDE\stdio.h 232: 
C:\BC45\INCLUDE\stdio.h 233: int      __cdecl  _fgetc(FILE  *__stream);           
C:\BC45\INCLUDE\stdio.h 234: int      __cdecl  _fputc(char __c, FILE  *__stream); 
C:\BC45\INCLUDE\stdio.h 235: void     __cdecl _InitEasyWin(void);  
C:\BC45\INCLUDE\stdio.h 236: 
C:\BC45\INCLUDE\stdio.h 237: 
C:\BC45\INCLUDE\stdio.h 238: 
C:\BC45\INCLUDE\stdio.h 239: 
C:\BC45\INCLUDE\stdio.h 240: 
C:\BC45\INCLUDE\stdio.h 241: 
C:\BC45\INCLUDE\stdio.h 242: 
C:\BC45\INCLUDE\stdio.h 243: 
C:\BC45\INCLUDE\stdio.h 244: 
C:\BC45\INCLUDE\stdio.h 245: 
C:\BC45\INCLUDE\stdio.h 246: 
C:\BC45\INCLUDE\stdio.h 247: 
C:\BC45\INCLUDE\stdio.h 248: 
C:\BC45\INCLUDE\stdio.h 249: 
C:\BC45\INCLUDE\stdio.h 250: 
C:\BC45\INCLUDE\stdio.h 251: 
C:\BC45\INCLUDE\stdio.h 252: 
C:\BC45\INCLUDE\stdio.h 253: 
C:\BC45\INCLUDE\stdio.h 254: 
C:\BC45\INCLUDE\stdio.h 255: 
C:\BC45\INCLUDE\stdio.h 256: 
C:\BC45\INCLUDE\stdio.h 257: 
C:\BC45\INCLUDE\stdio.h 258: 
C:\BC45\INCLUDE\stdio.h 259: 
C:\BC45\INCLUDE\stdio.h 260: 
C:\BC45\INCLUDE\stdio.h 261: 
C:\BC45\INCLUDE\stdio.h 262: 
C:\BC45\INCLUDE\stdio.h 263: 
C:\BC45\INCLUDE\stdio.h 264: 
C:\BC45\INCLUDE\stdio.h 265: 
C:\BC45\INCLUDE\stdio.h 266: 
C:\BC45\INCLUDE\stdio.h 267: 
C:\BC45\INCLUDE\stdio.h 268: 
C:\BC45\INCLUDE\stdio.h 269: 
C:\BC45\INCLUDE\stdio.h 270: 
C:\BC45\INCLUDE\stdio.h 271: 
C:\BC45\INCLUDE\stdio.h 272: 
C:\BC45\INCLUDE\stdio.h 273: 
C:\BC45\INCLUDE\stdio.h 274: 
C:\BC45\INCLUDE\stdio.h 275: 
C:\BC45\INCLUDE\stdio.h 276: 
C:\BC45\INCLUDE\stdio.h 277: 
C:\BC45\INCLUDE\stdio.h 278: 
C:\BC45\INCLUDE\stdio.h 279: 
C:\BC45\INCLUDE\stdio.h 280: 
C:\BC45\INCLUDE\stdio.h 281: 
C:\BC45\INCLUDE\stdio.h 282: 
C:\BC45\INCLUDE\stdio.h 283: 
C:\BC45\INCLUDE\stdio.h 284: 
C:\BC45\INCLUDE\stdio.h 285: 
C:\BC45\INCLUDE\stdio.h 286: 
C:\BC45\INCLUDE\stdio.h 287: 
C:\BC45\INCLUDE\stdio.h 288: 
C:\BC45\INCLUDE\stdio.h 289: 
C:\BC45\INCLUDE\stdio.h 290: 
C:\BC45\INCLUDE\stdio.h 291: 
C:\BC45\INCLUDE\stdio.h 292: 
C:\BC45\INCLUDE\stdio.h 293: 
C:\BC45\INCLUDE\stdio.h 294: 
C:\BC45\INCLUDE\stdio.h 295: 
C:\BC45\INCLUDE\stdio.h 296: 
C:\BC45\INCLUDE\stdio.h 297: 
C:\BC45\INCLUDE\stdio.h 298: 
C:\BC45\INCLUDE\stdio.h 299: 
C:\BC45\INCLUDE\stdio.h 300: 
C:\BC45\INCLUDE\stdio.h 301: 
C:\BC45\INCLUDE\stdio.h 302: 
C:\BC45\INCLUDE\stdio.h 303: 
C:\BC45\INCLUDE\stdio.h 304: 
C:\BC45\INCLUDE\stdio.h 305: 
C:\BC45\INCLUDE\stdio.h 306: 
C:\BC45\INCLUDE\stdio.h 307: 
C:\BC45\INCLUDE\stdio.h 308: 
C:\BC45\INCLUDE\stdio.h 309: 
C:\BC45\INCLUDE\stdio.h 310: 
C:\BC45\INCLUDE\stdio.h 311: 
C:\BC45\INCLUDE\stdio.h 312: 
C:\BC45\INCLUDE\stdio.h 313: 
C:\BC45\INCLUDE\stdio.h 314: 
C:\BC45\INCLUDE\stdio.h 315: 
C:\BC45\INCLUDE\stdio.h 316: 
C:\BC45\INCLUDE\stdio.h 317: 
C:\BC45\INCLUDE\stdio.h 318: 
C:\BC45\INCLUDE\stdio.h 319: 
C:\BC45\INCLUDE\stdio.h 320: 
C:\BC45\INCLUDE\stdio.h 321: 
C:\BC45\INCLUDE\stdio.h 322: 
C:\BC45\INCLUDE\stdio.h 323: 
C:\BC45\INCLUDE\stdio.h 324: 
C:\BC45\INCLUDE\stdio.h 325: 
C:\BC45\INCLUDE\stdio.h 326: 
C:\BC45\INCLUDE\stdio.h 327: 
C:\BC45\INCLUDE\stdio.h 328: 
C:\BC45\INCLUDE\stdio.h 329: 
C:\BC45\INCLUDE\stdio.h 330: 
C:\BC45\INCLUDE\stdio.h 331: 
C:\BC45\INCLUDE\stdio.h 332: 
C:\BC45\INCLUDE\stdio.h 333: 
C:\BC45\INCLUDE\stdio.h 334: 
C:\BC45\INCLUDE\stdio.h 335: 
C:\BC45\INCLUDE\stdio.h 336: 
C:\BC45\INCLUDE\stdio.h 337: 
C:\BC45\INCLUDE\stdio.h 338: 
C:\BC45\INCLUDE\stdio.h 339: 
C:\BC45\INCLUDE\stdio.h 340: 
C:\BC45\INCLUDE\stdio.h 341: 
C:\BC45\INCLUDE\stdio.h 342: 
C:\BC45\INCLUDE\stdio.h 343: 
C:\BC45\INCLUDE\stdio.h 344: 
C:\BC45\INCLUDE\stdio.h 345: 
C:\BC45\INCLUDE\stdio.h 346: 
C:\BC45\INCLUDE\stdio.h 347: 
C:\BC45\INCLUDE\stdio.h 348: 
C:\BC45\INCLUDE\stdio.h 349: 
C:\BC45\INCLUDE\stdio.h 350: 
C:\BC45\INCLUDE\stdio.h 351: 
C:\BC45\INCLUDE\stdio.h 352: 
C:\BC45\INCLUDE\stdio.h 353: 
C:\BC45\INCLUDE\stdio.h 354: 
C:\BC45\INCLUDE\stdio.h 355: 
C:\BC45\INCLUDE\stdio.h 356: 
C:\BC45\INCLUDE\stdio.h 357: 
C:\BC45\INCLUDE\stdio.h 358: 
C:\BC45\INCLUDE\stdio.h 359: 
C:\BC45\INCLUDE\stdio.h 360: 
C:\BC45\INCLUDE\stdio.h 361: 
C:\BC45\INCLUDE\stdio.h 362: 
C:\BC45\INCLUDE\stdio.h 363: 
C:\BC45\INCLUDE\stdio.h 364: 
C:\BC45\INCLUDE\stdio.h 365: 
C:\BC45\INCLUDE\stdio.h 366: 
C:\BC45\INCLUDE\stdio.h 367: 
C:\BC45\INCLUDE\stdio.h 368: 
C:\BC45\INCLUDE\stdio.h 369: 
C:\BC45\INCLUDE\stdio.h 370: 
C:\BC45\INCLUDE\stdio.h 371: 
C:\BC45\INCLUDE\stdio.h 372: 
C:\BC45\INCLUDE\stdio.h 373: 
C:\BC45\INCLUDE\stdio.h 374: 
C:\BC45\INCLUDE\stdio.h 375: 
C:\BC45\INCLUDE\stdio.h 376: 
C:\BC45\INCLUDE\stdio.h 377: 
C:\BC45\INCLUDE\stdio.h 378: 
C:\BC45\INCLUDE\stdio.h 379: 
C:\BC45\INCLUDE\stdio.h 380: 
C:\BC45\INCLUDE\stdio.h 381: 
C:\BC45\INCLUDE\stdio.h 382: 
C:\BC45\INCLUDE\stdio.h 383: 
C:\BC45\INCLUDE\stdio.h 384: 
C:\BC45\INCLUDE\stdio.h 385: 
C:\BC45\INCLUDE\stdio.h 386: 
C:\BC45\INCLUDE\stdio.h 387: 
C:\BC45\INCLUDE\stdio.h 388: 
C:\BC45\INCLUDE\stdio.h 389: 
C:\BC45\INCLUDE\stdio.h 390: 
C:\BC45\INCLUDE\stdio.h 391: #pragma option -a. /* restore default packing */
C:\BC45\INCLUDE\stdio.h 392: 
C:\BC45\INCLUDE\stdio.h 393: 
C:\BC45\INCLUDE\stdio.h 394: 
C:\BC45\INCLUDE\stdio.h 395: 
C:\BC45\INCLUDE\stdio.h 396: 
C:\BC45\INCLUDE\stdio.h 397: 
C:\BC45\INCLUDE\stdio.h 398: 
C:\BC45\INCLUDE\stdio.h 399: 
C:\BC45\INCLUDE\stdio.h 400: 
C:\BC45\INCLUDE\stdio.h 401: 
C:\BC45\INCLUDE\stdio.h 402: 
genplas.rad 21: 
C:\BC45\INCLUDE\math.h 1: 
C:\BC45\INCLUDE\math.h 2: 
C:\BC45\INCLUDE\math.h 3: 
C:\BC45\INCLUDE\math.h 4: 
C:\BC45\INCLUDE\math.h 5: 
C:\BC45\INCLUDE\math.h 6: 
C:\BC45\INCLUDE\math.h 7: 
C:\BC45\INCLUDE\math.h 8: 
C:\BC45\INCLUDE\math.h 9: 
C:\BC45\INCLUDE\math.h 10: 
C:\BC45\INCLUDE\math.h 11: 
C:\BC45\INCLUDE\math.h 12: 
C:\BC45\INCLUDE\math.h 13: 
C:\BC45\INCLUDE\math.h 14: 
C:\BC45\INCLUDE\math.h 15: 
C:\BC45\INCLUDE\math.h 16: 
C:\BC45\INCLUDE\math.h 17: 
C:\BC45\INCLUDE\math.h 18: 
C:\BC45\INCLUDE\math.h 19: 
C:\BC45\INCLUDE\math.h 20: 
C:\BC45\INCLUDE\math.h 21: 
C:\BC45\INCLUDE\math.h 22: 
C:\BC45\INCLUDE\math.h 23: 
C:\BC45\INCLUDE\math.h 24: 
C:\BC45\INCLUDE\math.h 25: 
C:\BC45\INCLUDE\math.h 26: 
C:\BC45\INCLUDE\math.h 27: 
C:\BC45\INCLUDE\math.h 28: 
C:\BC45\INCLUDE\math.h 29: #pragma option -a-
C:\BC45\INCLUDE\math.h 30: 
C:\BC45\INCLUDE\math.h 31: 
C:\BC45\INCLUDE\math.h 32: 
C:\BC45\INCLUDE\math.h 33: 
C:\BC45\INCLUDE\math.h 34:  
C:\BC45\INCLUDE\math.h 35: 
C:\BC45\INCLUDE\math.h 36: 
C:\BC45\INCLUDE\math.h 37: 
C:\BC45\INCLUDE\math.h 38: 
C:\BC45\INCLUDE\math.h 39: struct complex      
C:\BC45\INCLUDE\math.h 40: {
C:\BC45\INCLUDE\math.h 41: double  x, y;
C:\BC45\INCLUDE\math.h 42: };
C:\BC45\INCLUDE\math.h 43: 
C:\BC45\INCLUDE\math.h 44: struct _complexl    
C:\BC45\INCLUDE\math.h 45: {
C:\BC45\INCLUDE\math.h 46: long double  x, y;
C:\BC45\INCLUDE\math.h 47: };
C:\BC45\INCLUDE\math.h 48: 
C:\BC45\INCLUDE\math.h 49: 
C:\BC45\INCLUDE\math.h 50: 
C:\BC45\INCLUDE\math.h 51: 
C:\BC45\INCLUDE\math.h 52: 
C:\BC45\INCLUDE\math.h 53: 
C:\BC45\INCLUDE\math.h 54: 
C:\BC45\INCLUDE\math.h 55: typedef enum
C:\BC45\INCLUDE\math.h 56: {
C:\BC45\INCLUDE\math.h 57: DOMAIN = 1,    
C:\BC45\INCLUDE\math.h 58: SING,          
C:\BC45\INCLUDE\math.h 59: OVERFLOW,      
C:\BC45\INCLUDE\math.h 60: UNDERFLOW,     
C:\BC45\INCLUDE\math.h 61: TLOSS,         
C:\BC45\INCLUDE\math.h 62: PLOSS,         
C:\BC45\INCLUDE\math.h 63: STACKFAULT     
C:\BC45\INCLUDE\math.h 64: }   _mexcep;
C:\BC45\INCLUDE\math.h 65: 
C:\BC45\INCLUDE\math.h 66: 
C:\BC45\INCLUDE\math.h 67: 
C:\BC45\INCLUDE\math.h 68: 
C:\BC45\INCLUDE\math.h 69: 
C:\BC45\INCLUDE\math.h 70: 
C:\BC45\INCLUDE\math.h 71: 
C:\BC45\INCLUDE\math.h 72: 
C:\BC45\INCLUDE\math.h 73: 
C:\BC45\INCLUDE\math.h 74: 
C:\BC45\INCLUDE\math.h 75: 
C:\BC45\INCLUDE\math.h 76: 
C:\BC45\INCLUDE\math.h 77: 
C:\BC45\INCLUDE\math.h 78: 
C:\BC45\INCLUDE\math.h 79: 
C:\BC45\INCLUDE\math.h 80: 
C:\BC45\INCLUDE\math.h 81: 
C:\BC45\INCLUDE\math.h 82: 
C:\BC45\INCLUDE\math.h 83: 
C:\BC45\INCLUDE\math.h 84: 
C:\BC45\INCLUDE\math.h 85: struct  exception
C:\BC45\INCLUDE\math.h 86: {
C:\BC45\INCLUDE\math.h 87: int type;
C:\BC45\INCLUDE\math.h 88: char    *name;
C:\BC45\INCLUDE\math.h 89: double  arg1, arg2, retval;
C:\BC45\INCLUDE\math.h 90: };
C:\BC45\INCLUDE\math.h 91: 
C:\BC45\INCLUDE\math.h 92: struct  _exceptionl
C:\BC45\INCLUDE\math.h 93: {
C:\BC45\INCLUDE\math.h 94: int type;
C:\BC45\INCLUDE\math.h 95: char    *name;
C:\BC45\INCLUDE\math.h 96: long double  arg1, arg2, retval;
C:\BC45\INCLUDE\math.h 97: };
C:\BC45\INCLUDE\math.h 98: 
C:\BC45\INCLUDE\math.h 99: 
C:\BC45\INCLUDE\math.h 100: 
C:\BC45\INCLUDE\math.h 101: 
C:\BC45\INCLUDE\math.h 102: extern double __cdecl _huge_dble;
C:\BC45\INCLUDE\math.h 103: 
C:\BC45\INCLUDE\math.h 104: extern long double __cdecl _huge_ldble;
C:\BC45\INCLUDE\math.h 105: 
C:\BC45\INCLUDE\math.h 106: 
C:\BC45\INCLUDE\math.h 107: 
C:\BC45\INCLUDE\math.h 108: 
C:\BC45\INCLUDE\math.h 109: double      __cdecl  acos    (double __x);
C:\BC45\INCLUDE\math.h 110: double      __cdecl  asin    (double __x);
C:\BC45\INCLUDE\math.h 111: double      __cdecl          atan    (double __x);
C:\BC45\INCLUDE\math.h 112: double      __cdecl  atan2   (double __y, double __x);
C:\BC45\INCLUDE\math.h 113: double      __cdecl  ceil    (double __x);
C:\BC45\INCLUDE\math.h 114: double      __cdecl  cos     (double __x);
C:\BC45\INCLUDE\math.h 115: double      __cdecl  cosh    (double __x);
C:\BC45\INCLUDE\math.h 116: double      __cdecl  exp     (double __x);
C:\BC45\INCLUDE\math.h 117: double      __cdecl          fabs    (double __x);
C:\BC45\INCLUDE\math.h 118: double      __cdecl          __fabs__(double __x); 
C:\BC45\INCLUDE\math.h 119: double      __cdecl  floor   (double __x);
C:\BC45\INCLUDE\math.h 120: double      __cdecl  fmod    (double __x, double __y);
C:\BC45\INCLUDE\math.h 121: double      __cdecl  frexp   (double __x, int  *__exponent);
C:\BC45\INCLUDE\math.h 122: double      __cdecl  ldexp   (double __x, int __exponent);
C:\BC45\INCLUDE\math.h 123: double      __cdecl  log     (double __x);
C:\BC45\INCLUDE\math.h 124: double      __cdecl  log10   (double __x);
C:\BC45\INCLUDE\math.h 125: double      __cdecl  modf    (double __x, double  *__ipart);
C:\BC45\INCLUDE\math.h 126: double      __cdecl  pow     (double __x, double __y);
C:\BC45\INCLUDE\math.h 127: double      __cdecl  sin     (double __x);
C:\BC45\INCLUDE\math.h 128: double      __cdecl  sinh    (double __x);
C:\BC45\INCLUDE\math.h 129: double      __cdecl  sqrt    (double __x);
C:\BC45\INCLUDE\math.h 130: double      __cdecl  tan     (double __x);
C:\BC45\INCLUDE\math.h 131: double      __cdecl  tanh    (double __x);
C:\BC45\INCLUDE\math.h 132: 
C:\BC45\INCLUDE\math.h 133: long double __cdecl  acosl  (long double __x);
C:\BC45\INCLUDE\math.h 134: long double __cdecl  asinl  (long double __x);
C:\BC45\INCLUDE\math.h 135: long double __cdecl  atan2l (long double __x, long double __y);
C:\BC45\INCLUDE\math.h 136: long double __cdecl          atanl  (long double __x);
C:\BC45\INCLUDE\math.h 137: long double __cdecl  ceill  (long double __x);
C:\BC45\INCLUDE\math.h 138: long double __cdecl  coshl  (long double __x);
C:\BC45\INCLUDE\math.h 139: long double __cdecl  cosl   (long double __x);
C:\BC45\INCLUDE\math.h 140: long double __cdecl  expl   (long double __x);
C:\BC45\INCLUDE\math.h 141: long double __cdecl          fabsl  (long double __x);
C:\BC45\INCLUDE\math.h 142: long double __cdecl  floorl (long double __x);
C:\BC45\INCLUDE\math.h 143: long double __cdecl  fmodl  (long double __x, long double __y);
C:\BC45\INCLUDE\math.h 144: long double __cdecl  frexpl (long double __x, int  *__exponent);
C:\BC45\INCLUDE\math.h 145: long double __cdecl  ldexpl (long double __x, int __exponent);
C:\BC45\INCLUDE\math.h 146: long double __cdecl  log10l (long double __x);
C:\BC45\INCLUDE\math.h 147: long double __cdecl  logl   (long double __x);
C:\BC45\INCLUDE\math.h 148: long double __cdecl  modfl  (long double __x, long double  *__ipart);
C:\BC45\INCLUDE\math.h 149: long double __cdecl  powl   (long double __x, long double __y);
C:\BC45\INCLUDE\math.h 150: long double __cdecl  sinhl  (long double __x);
C:\BC45\INCLUDE\math.h 151: long double __cdecl  sinl   (long double __x);
C:\BC45\INCLUDE\math.h 152: long double __cdecl  sqrtl  (long double __x);
C:\BC45\INCLUDE\math.h 153: long double __cdecl  tanhl  (long double __x);
C:\BC45\INCLUDE\math.h 154: long double __cdecl  tanl   (long double __x);
C:\BC45\INCLUDE\math.h 155: 
C:\BC45\INCLUDE\math.h 156: 
C:\BC45\INCLUDE\math.h 157: 
C:\BC45\INCLUDE\math.h 158: 
C:\BC45\INCLUDE\math.h 159: 
C:\BC45\INCLUDE\math.h 160: 
C:\BC45\INCLUDE\math.h 161: 
C:\BC45\INCLUDE\math.h 162: 
C:\BC45\INCLUDE\math.h 163: 
C:\BC45\INCLUDE\math.h 164: 
C:\BC45\INCLUDE\math.h 165: 
C:\BC45\INCLUDE\math.h 166: 
C:\BC45\INCLUDE\math.h 167: double      __cdecl  hypot (double __x, double __y);
C:\BC45\INCLUDE\math.h 168: int         __cdecl  _matherr (struct exception  *__e);
C:\BC45\INCLUDE\math.h 169: double      __cdecl  poly  (double __x, int __degree, double  *__coeffs);
C:\BC45\INCLUDE\math.h 170: double      __cdecl  pow10 (int __p);
C:\BC45\INCLUDE\math.h 171: long double __cdecl  hypotl (long double __x, long double __y);
C:\BC45\INCLUDE\math.h 172: long double __cdecl  polyl  (long double __x, int __degree, long double  *__coeffs);
C:\BC45\INCLUDE\math.h 173: long double __cdecl  pow10l (int __p);
C:\BC45\INCLUDE\math.h 174: 
C:\BC45\INCLUDE\math.h 175: 
C:\BC45\INCLUDE\math.h 176: 
C:\BC45\INCLUDE\math.h 177: int         __cdecl __abs__(int);
C:\BC45\INCLUDE\math.h 178: 
C:\BC45\INCLUDE\math.h 179: 
C:\BC45\INCLUDE\math.h 180: 
C:\BC45\INCLUDE\math.h 181: int         __cdecl abs(int __x);
C:\BC45\INCLUDE\math.h 182: 
C:\BC45\INCLUDE\math.h 183: 
C:\BC45\INCLUDE\math.h 184: 
C:\BC45\INCLUDE\math.h 185: 
C:\BC45\INCLUDE\math.h 186: 
C:\BC45\INCLUDE\math.h 187: double      __cdecl          atof  (const char  *__s);
C:\BC45\INCLUDE\math.h 188: long        __cdecl          labs  (long __x);
C:\BC45\INCLUDE\math.h 189: int         __cdecl  _matherrl (struct _exceptionl  *__e);
C:\BC45\INCLUDE\math.h 190: 
C:\BC45\INCLUDE\math.h 191: long double __cdecl          _atold (const char  *__s);
C:\BC45\INCLUDE\math.h 192: 
C:\BC45\INCLUDE\math.h 193: long double __cdecl  hypotl (long double __x, long double __y);
C:\BC45\INCLUDE\math.h 194: long double __cdecl  polyl  (long double __x, int __degree, long double  *__coeffs);
C:\BC45\INCLUDE\math.h 195: long double __cdecl  pow10l (int __p);
C:\BC45\INCLUDE\math.h 196: 
C:\BC45\INCLUDE\math.h 197: 
C:\BC45\INCLUDE\math.h 198: 
C:\BC45\INCLUDE\math.h 199: 
C:\BC45\INCLUDE\math.h 200: 
C:\BC45\INCLUDE\math.h 201: 
C:\BC45\INCLUDE\math.h 202: 
C:\BC45\INCLUDE\math.h 203: 
C:\BC45\INCLUDE\math.h 204: 
C:\BC45\INCLUDE\math.h 205: 
C:\BC45\INCLUDE\math.h 206: 
C:\BC45\INCLUDE\math.h 207: 
C:\BC45\INCLUDE\math.h 208: 
C:\BC45\INCLUDE\math.h 209: 
C:\BC45\INCLUDE\math.h 210: 
C:\BC45\INCLUDE\math.h 211: 
C:\BC45\INCLUDE\math.h 212: 
C:\BC45\INCLUDE\math.h 213: 
C:\BC45\INCLUDE\math.h 214: 
C:\BC45\INCLUDE\math.h 215: 
C:\BC45\INCLUDE\math.h 216: 
C:\BC45\INCLUDE\math.h 217: 
C:\BC45\INCLUDE\math.h 218: 
C:\BC45\INCLUDE\math.h 219: 
C:\BC45\INCLUDE\math.h 220: 
C:\BC45\INCLUDE\math.h 221: 
C:\BC45\INCLUDE\math.h 222: 
C:\BC45\INCLUDE\math.h 223: 
C:\BC45\INCLUDE\math.h 224: 
C:\BC45\INCLUDE\math.h 225: 
C:\BC45\INCLUDE\math.h 226: 
C:\BC45\INCLUDE\math.h 227: 
C:\BC45\INCLUDE\math.h 228: 
C:\BC45\INCLUDE\math.h 229: 
C:\BC45\INCLUDE\math.h 230: 
C:\BC45\INCLUDE\math.h 231: 
C:\BC45\INCLUDE\math.h 232: 
C:\BC45\INCLUDE\math.h 233: 
C:\BC45\INCLUDE\math.h 234: 
C:\BC45\INCLUDE\math.h 235: 
C:\BC45\INCLUDE\math.h 236: 
C:\BC45\INCLUDE\math.h 237: 
C:\BC45\INCLUDE\math.h 238: 
C:\BC45\INCLUDE\math.h 239: 
C:\BC45\INCLUDE\math.h 240: 
C:\BC45\INCLUDE\math.h 241: 
C:\BC45\INCLUDE\math.h 242: 
C:\BC45\INCLUDE\math.h 243: 
C:\BC45\INCLUDE\math.h 244: 
C:\BC45\INCLUDE\math.h 245: 
C:\BC45\INCLUDE\math.h 246: 
C:\BC45\INCLUDE\math.h 247: 
C:\BC45\INCLUDE\math.h 248: 
C:\BC45\INCLUDE\math.h 249: 
C:\BC45\INCLUDE\math.h 250: 
C:\BC45\INCLUDE\math.h 251: 
C:\BC45\INCLUDE\math.h 252: 
C:\BC45\INCLUDE\math.h 253: 
C:\BC45\INCLUDE\math.h 254: 
C:\BC45\INCLUDE\math.h 255: 
C:\BC45\INCLUDE\math.h 256: 
C:\BC45\INCLUDE\math.h 257: 
C:\BC45\INCLUDE\math.h 258: 
C:\BC45\INCLUDE\math.h 259: 
C:\BC45\INCLUDE\math.h 260: 
C:\BC45\INCLUDE\math.h 261: 
C:\BC45\INCLUDE\math.h 262: 
C:\BC45\INCLUDE\math.h 263: 
C:\BC45\INCLUDE\math.h 264: 
C:\BC45\INCLUDE\math.h 265: 
C:\BC45\INCLUDE\math.h 266: 
C:\BC45\INCLUDE\math.h 267: 
C:\BC45\INCLUDE\math.h 268: 
C:\BC45\INCLUDE\math.h 269: 
C:\BC45\INCLUDE\math.h 270: 
C:\BC45\INCLUDE\math.h 271: 
C:\BC45\INCLUDE\math.h 272: 
C:\BC45\INCLUDE\math.h 273: 
C:\BC45\INCLUDE\math.h 274: 
C:\BC45\INCLUDE\math.h 275: 
C:\BC45\INCLUDE\math.h 276: 
C:\BC45\INCLUDE\math.h 277: 
C:\BC45\INCLUDE\math.h 278: 
C:\BC45\INCLUDE\math.h 279: 
C:\BC45\INCLUDE\math.h 280: 
C:\BC45\INCLUDE\math.h 281: 
C:\BC45\INCLUDE\math.h 282: 
C:\BC45\INCLUDE\math.h 283: 
C:\BC45\INCLUDE\math.h 284: 
C:\BC45\INCLUDE\math.h 285: 
C:\BC45\INCLUDE\math.h 286: 
C:\BC45\INCLUDE\math.h 287: 
C:\BC45\INCLUDE\math.h 288: 
C:\BC45\INCLUDE\math.h 289: 
C:\BC45\INCLUDE\math.h 290: 
C:\BC45\INCLUDE\math.h 291: 
C:\BC45\INCLUDE\math.h 292: 
C:\BC45\INCLUDE\math.h 293: 
C:\BC45\INCLUDE\math.h 294: 
C:\BC45\INCLUDE\math.h 295: 
C:\BC45\INCLUDE\math.h 296: 
C:\BC45\INCLUDE\math.h 297: 
C:\BC45\INCLUDE\math.h 298: 
C:\BC45\INCLUDE\math.h 299: 
C:\BC45\INCLUDE\math.h 300: 
C:\BC45\INCLUDE\math.h 301: 
C:\BC45\INCLUDE\math.h 302: 
C:\BC45\INCLUDE\math.h 303: 
C:\BC45\INCLUDE\math.h 304: 
C:\BC45\INCLUDE\math.h 305: 
C:\BC45\INCLUDE\math.h 306: 
C:\BC45\INCLUDE\math.h 307: 
C:\BC45\INCLUDE\math.h 308: 
C:\BC45\INCLUDE\math.h 309: 
C:\BC45\INCLUDE\math.h 310: 
C:\BC45\INCLUDE\math.h 311: 
C:\BC45\INCLUDE\math.h 312: 
C:\BC45\INCLUDE\math.h 313: 
C:\BC45\INCLUDE\math.h 314: 
C:\BC45\INCLUDE\math.h 315: #pragma option -a. /* restore default packing */
C:\BC45\INCLUDE\math.h 316: 
C:\BC45\INCLUDE\math.h 317: 
C:\BC45\INCLUDE\math.h 318: 
C:\BC45\INCLUDE\math.h 319: 
C:\BC45\INCLUDE\math.h 320: 
C:\BC45\INCLUDE\math.h 321: 
C:\BC45\INCLUDE\math.h 322: 
C:\BC45\INCLUDE\math.h 323: 
C:\BC45\INCLUDE\math.h 324: 
C:\BC45\INCLUDE\math.h 325: 
C:\BC45\INCLUDE\math.h 326: 
C:\BC45\INCLUDE\math.h 327: 
C:\BC45\INCLUDE\math.h 328: 
C:\BC45\INCLUDE\math.h 329: 
genplas.rad 22: 
genplas.rad 23: void	main()
genplas.rad 24: {
genplas.rad 25: float	x,y,count,i;
genplas.rad 26: int	lead,offset;
genplas.rad 27: FILE	*fp;
genplas.rad 28: unsigned char value;
genplas.rad 29: 
genplas.rad 30: printf("\nJCL-plasma Generator 1.1L (C) JCL-Software 1994\n\nHang in there ...!\n");
genplas.rad 31: 
genplas.rad 32: if (!(fp=fopen("PLASMA.DAT","wb")))
genplas.rad 33: {
genplas.rad 34: printf("\7Cant open output file PLASMA.DAT\n");
genplas.rad 35: exit(255);
genplas.rad 36: }
genplas.rad 37: 
genplas.rad 38: 
genplas.rad 39: 
genplas.rad 40: 
genplas.rad 41: 
genplas.rad 42: 
genplas.rad 43: for (y=0;y<300;y++)
genplas.rad 44: for (x=0;x<512;x++)
genplas.rad 45: {
genplas.rad 46: value=64+10*( sin(x/30) + cos(y/46) +
genplas.rad 47: cos(x/27) + sin(y/60) +
genplas.rad 48: sin((x+y)/63) +
genplas.rad 49: cos(hypot(256-x,150-y)/12)
genplas.rad 50: );
genplas.rad 51: fputc(value,fp);
genplas.rad 52: }
genplas.rad 53: 
genplas.rad 54: 
genplas.rad 55: 
genplas.rad 56: for (count=0;count<10000;count++)
genplas.rad 57: {
genplas.rad 58: lead=           96+92*cos(count/20)
genplas.rad 59: +512*(int)(48+47*sin(count/16));
genplas.rad 60: offset=         96+92*sin(count/41)
genplas.rad 61: +512*(int)(48+47*cos(count/14))
genplas.rad 62: -lead;
genplas.rad 63: fwrite(&lead,2,1,fp);
genplas.rad 64: fwrite(&offset,2,1,fp);
genplas.rad 65: }
genplas.rad 66: 
genplas.rad 67: 
genplas.rad 68: 
genplas.rad 69: for (i=-256; i<256*39; i++)
genplas.rad 70: if (i<0)
genplas.rad 71: {
genplas.rad 72: fputc(0,fp);
genplas.rad 73: fputc(0,fp);
genplas.rad 74: fputc(0,fp);
genplas.rad 75: }
genplas.rad 76: else
genplas.rad 77: {
genplas.rad 78: fputc((sin(i/20)*sin(i/15)*31+31),fp);
genplas.rad 79: fputc((sin(i/35)*sin(i/22)*31+31),fp);
genplas.rad 80: fputc((sin(i/13)*sin(i/30)*31+31),fp);
genplas.rad 81: }
genplas.rad 82: fclose(fp);
genplas.rad 83: }
genplas.rad 84: 
genplas.rad 85: 